version: "3.8"
services:
  news-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: news-app-prod
    ports:
      - '8080:80'
    volumes:
      - ./src:/app/news-app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./.env.production.local
