FROM node:20-alpine AS build

WORKDIR /app/news-app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:1.25.4-alpine
COPY --from=build /app/news-app/dist /usr/share/nginx/html
