import ArticlesList from "../features/articles/components/ArticlesList.tsx";

const articles = [
	{
		uri: "nyt://interactive/823567ca-2ff0-5e78-9407-bdfebf7eb7c8",
		image: "",
		url: "https://www.nytimes.com/interactive/2024/02/13/us/elections/results-new-york-us-house-3-special.html",
		id: 100000009311989,
		asset_id: 100000009311989,
		source: "New York Times",
		date: "2024-02-13",
		updated: "2024-02-15 14:57:13",
		section: "U.S.",
		subsection: "2024 Elections",
		nytdsection: "u.s.",
		adx_keywords:
			"internal-paywall-exempt;Elections, House of Representatives;Elections;Elections;Suozzi, Thomas R;Pilip, Mazi Melesa;New York;Long Island (NY)",
		column: null,
		author: "",
		type: "Interactive",
		title: "New York Third Congressional District Special Election Results",
		abstract: "Get live results and maps from the New York special election to replace George Santos.",
		des_facet: ["internal-paywall-exempt", "Elections, House of Representatives", "Elections", "Elections"],
		org_facet: [],
		per_facet: ["Suozzi, Thomas R", "Pilip, Mazi Melesa"],
		geo_facet: ["New York", "Long Island (NY)"],
		media: [
			{
				type: "image",
				subtype: "",
				caption: "",
				copyright: "",
				approved_for_syndication: 1,
				"media-metadata": [
					{
						url: "https://static01.nyt.com/images/2024/02/14/multimedia/eln-promo-2024-02-13-race-ny-us-h-CALL-suozzit/eln-promo-2024-02-13-race-ny-us-h-CALL-suozzit-thumbStandard.jpg",
						format: "Standard Thumbnail",
						height: 75,
						width: 75,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/14/multimedia/eln-promo-2024-02-13-race-ny-us-h-CALL-suozzit/eln-promo-2024-02-13-race-ny-us-h-CALL-suozzit-mediumThreeByTwo210.jpg",
						format: "mediumThreeByTwo210",
						height: 140,
						width: 210,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/14/multimedia/eln-promo-2024-02-13-race-ny-us-h-CALL-suozzit/eln-promo-2024-02-13-race-ny-us-h-CALL-suozzit-mediumThreeByTwo440.jpg",
						format: "mediumThreeByTwo440",
						height: 293,
						width: 440,
					},
				],
			},
		],
		eta_id: 0,
	},
	{
		uri: "nyt://interactive/73a69718-d4a6-520f-90d9-b306f97c2cc1",
		image: "",
		url: "https://www.nytimes.com/interactive/2024/02/13/climate/flooding-sea-levels-groundwater.html",
		id: 100000009306646,
		asset_id: 100000009306646,
		source: "New York Times",
		date: "2024-02-13",
		updated: "2024-02-16 09:46:24",
		section: "Climate",
		subsection: "",
		nytdsection: "climate",
		adx_keywords: "Coast Erosion;Coastal Areas;Floods;Aquifers;Conservation of Resources;East Coast (US)",
		column: null,
		author: "By Mira Rojanasakul and Marco Hernandez",
		type: "Interactive",
		title: "The East Coast Is Sinking",
		abstract: "Land is slumping into the ocean, compounding the dangers from sea level rise. A major culprit: overpumping of groundwater.",
		des_facet: ["Coast Erosion", "Coastal Areas", "Floods", "Aquifers", "Conservation of Resources"],
		org_facet: [],
		per_facet: [],
		geo_facet: ["East Coast (US)"],
		media: [
			{
				type: "image",
				subtype: "",
				caption: "",
				copyright: "The New York Times",
				approved_for_syndication: 1,
				"media-metadata": [
					{
						url: "https://static01.nyt.com/images/2024/02/08/multimedia/2024-01-04-atlantic-subsidence-index/2024-01-04-atlantic-subsidence-index-thumbStandard-v2.jpg",
						format: "Standard Thumbnail",
						height: 75,
						width: 75,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/08/multimedia/2024-01-04-atlantic-subsidence-index/2024-01-04-atlantic-subsidence-index-mediumThreeByTwo210-v3.jpg",
						format: "mediumThreeByTwo210",
						height: 140,
						width: 210,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/08/multimedia/2024-01-04-atlantic-subsidence-index/2024-01-04-atlantic-subsidence-index-mediumThreeByTwo440-v3.jpg",
						format: "mediumThreeByTwo440",
						height: 293,
						width: 440,
					},
				],
			},
		],
		eta_id: 0,
	},
	{
		uri: "nyt://article/a10e95d6-fa38-544b-9c81-78bf49f5f1dd",
		image: "",
		url: "https://www.nytimes.com/2024/02/12/us/winter-storm-snow-rain-forecast-noreaster.html",
		id: 100000009308407,
		asset_id: 100000009308407,
		source: "New York Times",
		date: "2024-02-12",
		updated: "2024-02-13 12:30:17",
		section: "U.S.",
		subsection: "",
		nytdsection: "u.s.",
		adx_keywords:
			"Snow and Snowstorms;Floods;Northeastern States (US);Poconos (Pa);Catskills (NYS Area);New Jersey;Long Island (NY);New York City;Connecticut;New York Metropolitan Area",
		column: null,
		author: "By Rebecca Carballo and Judson Jones",
		type: "Article",
		title: "Nor’easter Expected to Bring New York City’s Heaviest Snow in Over 2 Years",
		abstract: "A storm starting Monday night will bring heavy snow to parts of New Jersey, New York and Connecticut, forecasters said.",
		des_facet: ["Snow and Snowstorms", "Floods"],
		org_facet: [],
		per_facet: [],
		geo_facet: [
			"Northeastern States (US)",
			"Poconos (Pa)",
			"Catskills (NYS Area)",
			"New Jersey",
			"Long Island (NY)",
			"New York City",
			"Connecticut",
			"New York Metropolitan Area",
		],
		media: [
			{
				type: "image",
				subtype: "photo",
				caption: "",
				copyright: "",
				approved_for_syndication: 1,
				"media-metadata": [
					{
						url: "https://static01.nyt.com/images/2022/02/04/us/snow-forecast-totals-lookup-promo-1644020582331/snow-forecast-totals-lookup-promo-1644020582331-thumbStandard-v10.jpg",
						format: "Standard Thumbnail",
						height: 75,
						width: 75,
					},
					{
						url: "https://static01.nyt.com/images/2022/02/04/us/snow-forecast-totals-lookup-promo-1644020582331/snow-forecast-totals-lookup-promo-1644020582331-mediumThreeByTwo210-v7.jpg",
						format: "mediumThreeByTwo210",
						height: 140,
						width: 210,
					},
					{
						url: "https://static01.nyt.com/images/2022/02/04/us/snow-forecast-totals-lookup-promo-1644020582331/snow-forecast-totals-lookup-promo-1644020582331-mediumThreeByTwo440-v7.jpg",
						format: "mediumThreeByTwo440",
						height: 293,
						width: 440,
					},
				],
			},
		],
		eta_id: 0,
	},
	{
		uri: "nyt://article/dc07fd6b-1eea-5fbd-aad7-7ed47a9b4d0b",
		image: "",
		url: "https://www.nytimes.com/2024/02/14/business/angela-chao-dead.html",
		id: 100000009311006,
		asset_id: 100000009311006,
		source: "New York Times",
		date: "2024-02-14",
		updated: "2024-02-15 23:14:20",
		section: "Business",
		subsection: "",
		nytdsection: "business",
		adx_keywords: "International Relations;Deaths (Obituaries);Ships and Shipping;Chao, Angela;Foremost Group;China;United States",
		column: null,
		author: "By Keith Bradsher and Michael Forsythe",
		type: "Article",
		title: "Angela Chao, C.E.O. of Family’s Shipping Company, Is Dead at 50",
		abstract:
			"Ms. Chao, whose sister Elaine Chao was President Trump’s secretary of transportation, led Foremost Group, operator of a global fleet of freighters. She died in a car crash.",
		des_facet: ["International Relations", "Deaths (Obituaries)", "Ships and Shipping"],
		org_facet: ["Foremost Group"],
		per_facet: ["Chao, Angela"],
		geo_facet: ["China", "United States"],
		media: [
			{
				type: "image",
				subtype: "photo",
				caption: "Angela Chao at New York City Opera’s Fall Gala at Lincoln Center in 2010.",
				copyright: "Adriel Reboh/Patrick McMullan, via Getty Images",
				approved_for_syndication: 1,
				"media-metadata": [
					{
						url: "https://static01.nyt.com/images/2024/02/16/business/00Chao-Obit-print1/00Chao-Obit-thumbStandard.jpg",
						format: "Standard Thumbnail",
						height: 75,
						width: 75,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/16/business/00Chao-Obit-print1/00Chao-Obit-mediumThreeByTwo210.jpg",
						format: "mediumThreeByTwo210",
						height: 140,
						width: 210,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/16/business/00Chao-Obit-print1/00Chao-Obit-mediumThreeByTwo440.jpg",
						format: "mediumThreeByTwo440",
						height: 293,
						width: 440,
					},
				],
			},
		],
		eta_id: 0,
	},
	{
		uri: "nyt://article/d3ce5bf7-6beb-5426-9e3d-7fbf5e2f9c21",
		image: "",
		url: "https://www.nytimes.com/2024/02/16/us/politics/trump-abortion-ban.html",
		id: 100000009316953,
		asset_id: 100000009316953,
		source: "New York Times",
		date: "2024-02-16",
		updated: "2024-02-19 13:42:36",
		section: "U.S.",
		subsection: "Politics",
		nytdsection: "u.s.",
		adx_keywords:
			"Abortion;Presidential Election of 2024;Roe v Wade (Supreme Court Decision);Dobbs v Jackson Women's Health Organization (Supreme Court Decision);United States Politics and Government;Polls and Public Opinion;Trump, Donald J;Republican Party",
		column: null,
		author: "By Maggie Haberman, Jonathan Swan and Lisa Lerer",
		type: "Article",
		title: "Trump Privately Expresses Support for a 16-Week Abortion Ban",
		abstract:
			"In supporting a 16-week ban with exceptions, Donald Trump appears to be trying to satisfy social conservatives who want to further restrict abortion access and voters who want more modest limits.",
		des_facet: [
			"Abortion",
			"Presidential Election of 2024",
			"Roe v Wade (Supreme Court Decision)",
			"Dobbs v Jackson Women's Health Organization (Supreme Court Decision)",
			"United States Politics and Government",
			"Polls and Public Opinion",
		],
		org_facet: ["Republican Party"],
		per_facet: ["Trump, Donald J"],
		geo_facet: [],
		media: [
			{
				type: "image",
				subtype: "photo",
				caption: "Donald J. Trump has studiously avoided taking a clear position on restrictions to abortion since Roe v. Wade was overturned.",
				copyright: "Kendrick Brinson for The New York Times",
				approved_for_syndication: 1,
				"media-metadata": [
					{
						url: "https://static01.nyt.com/images/2024/02/16/multimedia/16Trump-abortion-tpfq/16Trump-abortion-tpfq-thumbStandard.jpg",
						format: "Standard Thumbnail",
						height: 75,
						width: 75,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/16/multimedia/16Trump-abortion-tpfq/16Trump-abortion-tpfq-mediumThreeByTwo210.jpg",
						format: "mediumThreeByTwo210",
						height: 140,
						width: 210,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/16/multimedia/16Trump-abortion-tpfq/16Trump-abortion-tpfq-mediumThreeByTwo440.jpg",
						format: "mediumThreeByTwo440",
						height: 293,
						width: 440,
					},
				],
			},
		],
		eta_id: 0,
	},
	{
		uri: "nyt://article/a02ead71-f7e6-59c8-ab14-87e216d53a16",
		image: "",
		url: "https://www.nytimes.com/article/kansas-city-parade-shooting.html",
		id: 100000009314612,
		asset_id: 100000009314612,
		source: "New York Times",
		date: "2024-02-15",
		updated: "2024-02-17 12:34:41",
		section: "U.S.",
		subsection: "",
		nytdsection: "u.s.",
		adx_keywords: "Kansas City, Mo, Shooting (Feb 14, 2024);Parades;Football;Super Bowl;Kansas City Chiefs;Kansas City (Mo)",
		column: null,
		author: "By The New York Times",
		type: "Article",
		title: "The Kansas City Super Bowl Parade Shooting: What We Know",
		abstract: "The eruption of violence in Kansas City, Mo., came as thousands of people had gathered for a public celebration.",
		des_facet: ["Kansas City, Mo, Shooting (Feb 14, 2024)", "Parades", "Football", "Super Bowl"],
		org_facet: ["Kansas City Chiefs"],
		per_facet: [],
		geo_facet: ["Kansas City (Mo)"],
		media: [
			{
				type: "image",
				subtype: "photo",
				caption: "A shooting near Kansas City’s Union Station erupted on Wednesday after the Super Bowl parade.",
				copyright: "Christopher (KS) Smith for The New York Times",
				approved_for_syndication: 1,
				"media-metadata": [
					{
						url: "https://static01.nyt.com/images/2024/02/14/multimedia/14nat-kc-shooting-wwk-mtqv/14nat-kc-shooting-wwk-mtqv-thumbStandard.jpg",
						format: "Standard Thumbnail",
						height: 75,
						width: 75,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/14/multimedia/14nat-kc-shooting-wwk-mtqv/14nat-kc-shooting-wwk-mtqv-mediumThreeByTwo210.jpg",
						format: "mediumThreeByTwo210",
						height: 140,
						width: 210,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/14/multimedia/14nat-kc-shooting-wwk-mtqv/14nat-kc-shooting-wwk-mtqv-mediumThreeByTwo440.jpg",
						format: "mediumThreeByTwo440",
						height: 293,
						width: 440,
					},
				],
			},
		],
		eta_id: 0,
	},
	{
		uri: "nyt://article/2ccc8906-7561-56ff-9694-9a74800655f8",
		image: "",
		url: "https://www.nytimes.com/2024/02/17/us/politics/jimmy-carter-hospice-anniversary.html",
		id: 100000009318665,
		asset_id: 100000009318665,
		source: "New York Times",
		date: "2024-02-17",
		updated: "2024-02-17 22:58:04",
		section: "U.S.",
		subsection: "Politics",
		nytdsection: "u.s.",
		adx_keywords: "United States Politics and Government;Elder Care;Hospice Care;Carter, Jimmy;Carter, Jason (1975- );Carter, Rosalynn",
		column: null,
		author: "By Peter Baker",
		type: "Article",
		title: "Jimmy Carter’s Long Goodbye",
		abstract:
			"The former president is on the verge of having spent a year in hospice care, once again confounding expectations in a life that has lasted nearly a century.",
		des_facet: ["United States Politics and Government", "Elder Care", "Hospice Care"],
		org_facet: [],
		per_facet: ["Carter, Jimmy", "Carter, Jason (1975- )", "Carter, Rosalynn"],
		geo_facet: [],
		media: [
			{
				type: "image",
				subtype: "photo",
				caption:
					"Before he entered hospice care, thousands came to the Maranatha Baptist Church in Plains, Ga., to hear former President Jimmy Carter teach Sunday school. Here he greeted a crowd in 2018.",
				copyright: "Melissa Golden for The New York Times",
				approved_for_syndication: 1,
				"media-metadata": [
					{
						url: "https://static01.nyt.com/images/2024/02/17/multimedia/17dc-carter-01-vbcj/17dc-carter-01-vbcj-thumbStandard.jpg",
						format: "Standard Thumbnail",
						height: 75,
						width: 75,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/17/multimedia/17dc-carter-01-vbcj/17dc-carter-01-vbcj-mediumThreeByTwo210.jpg",
						format: "mediumThreeByTwo210",
						height: 140,
						width: 210,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/17/multimedia/17dc-carter-01-vbcj/17dc-carter-01-vbcj-mediumThreeByTwo440.jpg",
						format: "mediumThreeByTwo440",
						height: 293,
						width: 440,
					},
				],
			},
		],
		eta_id: 0,
	},
	{
		uri: "nyt://article/93ecc55e-cad5-5e34-8733-a4a3d1af4131",
		image: "",
		url: "https://www.nytimes.com/2024/02/17/world/europe/aleksei-navalny-dead.html",
		id: 100000009319007,
		asset_id: 100000009319007,
		source: "New York Times",
		date: "2024-02-17",
		updated: "2024-02-17 21:40:58",
		section: "World",
		subsection: "Europe",
		nytdsection: "world",
		adx_keywords: "Deaths (Fatalities);Political Prisoners;vis-video;Navalny, Aleksei A;Putin, Vladimir V;Russia",
		column: null,
		author: "By Ivan Nechepurenko",
		type: "Article",
		title: "Aleksei Navalny’s Allies Confirm His Death as Russia Detains Mourners",
		abstract:
			"A spokeswoman for the team that has continued Mr. Navalny’s work said his mother had received the official notification. Hundreds of his mourners have been detained after his death.",
		des_facet: ["Deaths (Fatalities)", "Political Prisoners", "vis-video"],
		org_facet: [],
		per_facet: ["Navalny, Aleksei A", "Putin, Vladimir V"],
		geo_facet: ["Russia"],
		media: [
			{
				type: "image",
				subtype: "photo",
				caption:
					"Lyudmila Navalnaya, the mother of Aleksei A. Navalny, and one of his lawyers, Vasily Dubkov, arriving Saturday at the regional department of Russia’s Investigative Committee on Saturday in Salekhard, Russia.",
				copyright: "Maxim Shemetov/Reuters",
				approved_for_syndication: 1,
				"media-metadata": [
					{
						url: "https://static01.nyt.com/images/2024/02/17/multimedia/17navalny-zbvw/17navalny-zbvw-thumbStandard.jpg",
						format: "Standard Thumbnail",
						height: 75,
						width: 75,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/17/multimedia/17navalny-zbvw/17navalny-zbvw-mediumThreeByTwo210.jpg",
						format: "mediumThreeByTwo210",
						height: 140,
						width: 210,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/17/multimedia/17navalny-zbvw/17navalny-zbvw-mediumThreeByTwo440.jpg",
						format: "mediumThreeByTwo440",
						height: 293,
						width: 440,
					},
				],
			},
		],
		eta_id: 0,
	},
	{
		uri: "nyt://article/7f555355-0014-5a36-abce-38b6b50920a7",
		image: "",
		url: "https://www.nytimes.com/2024/02/15/us/politics/fbi-informant-bidens-ukraine.html",
		id: 100000009316275,
		asset_id: 100000009316275,
		source: "New York Times",
		date: "2024-02-15",
		updated: "2024-02-16 11:49:40",
		section: "U.S.",
		subsection: "Politics",
		nytdsection: "u.s.",
		adx_keywords:
			"United States Politics and Government;Informers;Rumors and Misinformation;Smirnov, Alexander (Informant);Biden, Hunter;Biden, Joseph R Jr;Weiss, David C (1956- );Federal Bureau of Investigation;Justice Department;Republican Party;Burisma Holdings Ltd",
		column: null,
		author: "By Glenn Thrush",
		type: "Article",
		title: "Ex-F.B.I. Informant Is Charged With Lying Over Bidens’ Role in Ukraine Business",
		abstract:
			"The informant’s story was part of a series of explosive and unsubstantiated claims by Republicans that the Bidens engaged in potentially criminal activity.",
		des_facet: ["United States Politics and Government", "Informers", "Rumors and Misinformation"],
		org_facet: ["Federal Bureau of Investigation", "Justice Department", "Republican Party", "Burisma Holdings Ltd"],
		per_facet: ["Smirnov, Alexander (Informant)", "Biden, Hunter", "Biden, Joseph R Jr", "Weiss, David C (1956- )"],
		geo_facet: [],
		media: [
			{
				type: "image",
				subtype: "photo",
				caption:
					"Hunter Biden outside the U.S. Capitol building in December. An FBI informant has been charged with lying to his handler about ties between Joe Biden and son Hunter and a Ukrainian energy company.",
				copyright: "Kenny Holston/The New York Times",
				approved_for_syndication: 1,
				"media-metadata": [
					{
						url: "https://static01.nyt.com/images/2024/02/15/multimedia/15dc-hunter-wmzj/15dc-hunter-wmzj-thumbStandard.jpg",
						format: "Standard Thumbnail",
						height: 75,
						width: 75,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/15/multimedia/15dc-hunter-wmzj/15dc-hunter-wmzj-mediumThreeByTwo210.jpg",
						format: "mediumThreeByTwo210",
						height: 140,
						width: 210,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/15/multimedia/15dc-hunter-wmzj/15dc-hunter-wmzj-mediumThreeByTwo440.jpg",
						format: "mediumThreeByTwo440",
						height: 293,
						width: 440,
					},
				],
			},
		],
		eta_id: 0,
	},
	{
		uri: "nyt://interactive/10595ec4-a756-56da-bfef-02274da8017a",
		image: "",
		url: "https://www.nytimes.com/interactive/2024/02/13/magazine/oscars-actors-free-time.html",
		id: 100000009310552,
		asset_id: 100000009310552,
		source: "New York Times",
		date: "2024-02-13",
		updated: "2024-02-18 13:23:19",
		section: "Magazine",
		subsection: "",
		nytdsection: "magazine",
		adx_keywords:
			"Actors and Actresses;Cooper, Bradley;Randolph, Da'Vine Joy;Wright, Jeffrey (1965- );Giamatti, Paul;Ruffalo, Mark;Bening, Annette;Ellis-Taylor, Aunjanue;Melton, Charles (1991- );Mulligan, Carey;Taylor, Teyana (1990- );Stone, Emma;Rogowski, Franz;Nachtwey, James",
		column: null,
		author: "Photographs by James Nachtwey",
		type: "Interactive",
		title: "Actors in the Wild",
		abstract: "The best performers of the year — when they’re not on film.",
		des_facet: ["Actors and Actresses"],
		org_facet: [],
		per_facet: [
			"Cooper, Bradley",
			"Randolph, Da'Vine Joy",
			"Wright, Jeffrey (1965- )",
			"Giamatti, Paul",
			"Ruffalo, Mark",
			"Bening, Annette",
			"Ellis-Taylor, Aunjanue",
			"Melton, Charles (1991- )",
			"Mulligan, Carey",
			"Taylor, Teyana (1990- )",
			"Stone, Emma",
			"Rogowski, Franz",
			"Nachtwey, James",
		],
		geo_facet: [],
		media: [
			{
				type: "image",
				subtype: "",
				caption: "",
				copyright: "James Nachtwey for The New York Times",
				approved_for_syndication: 1,
				"media-metadata": [
					{
						url: "https://static01.nyt.com/images/2024/02/18/magazine/18mag-portfolio/18mag-portfolio-thumbStandard.jpg",
						format: "Standard Thumbnail",
						height: 75,
						width: 75,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/18/magazine/18mag-portfolio/18mag-portfolio-mediumThreeByTwo210.jpg",
						format: "mediumThreeByTwo210",
						height: 140,
						width: 210,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/18/magazine/18mag-portfolio/18mag-portfolio-mediumThreeByTwo440.jpg",
						format: "mediumThreeByTwo440",
						height: 293,
						width: 440,
					},
				],
			},
		],
		eta_id: 0,
	},
	{
		uri: "nyt://article/3bcd5528-94bb-5e1b-9df2-a4f742fe803e",
		image: "",
		url: "https://www.nytimes.com/2024/02/18/realestate/trump-condos-prices-nyc.html",
		id: 100000009314391,
		asset_id: 100000009314391,
		source: "New York Times",
		date: "2024-02-18",
		updated: "2024-02-18 22:10:29",
		section: "Real Estate",
		subsection: "",
		nytdsection: "real estate",
		adx_keywords:
			"Real Estate and Housing (Residential);Condominiums;Trademarks and Trade Names;Suits and Litigation (Civil);Trump, Donald J;CityRealty.com;Trump Organization;Trump Tower (Manhattan, NY);Manhattan (NYC)",
		column: null,
		author: "By Rukmini Callimachi",
		type: "Article",
		title: "In New York, the Trump Brand Is Costing Some Condo Owners",
		abstract: "When Donald J. Trump became president, condominiums in buildings emblazoned with his name began selling for less, according to an analysis.",
		des_facet: ["Real Estate and Housing (Residential)", "Condominiums", "Trademarks and Trade Names", "Suits and Litigation (Civil)"],
		org_facet: ["CityRealty.com", "Trump Organization", "Trump Tower (Manhattan, NY)"],
		per_facet: ["Trump, Donald J"],
		geo_facet: ["Manhattan (NYC)"],
		media: [
			{
				type: "image",
				subtype: "photo",
				caption: "Condos in buildings branded with the Trump logo, like this one, have dropped in price in recent years. ",
				copyright: "Ahmed Gaber for The New York Times",
				approved_for_syndication: 1,
				"media-metadata": [
					{
						url: "https://static01.nyt.com/images/2024/02/18/multimedia/18trumpbrand8-wmpj/18trumpbrand8-wmpj-thumbStandard.jpg",
						format: "Standard Thumbnail",
						height: 75,
						width: 75,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/18/multimedia/18trumpbrand8-wmpj/18trumpbrand8-wmpj-mediumThreeByTwo210.jpg",
						format: "mediumThreeByTwo210",
						height: 140,
						width: 210,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/18/multimedia/18trumpbrand8-wmpj/18trumpbrand8-wmpj-mediumThreeByTwo440.jpg",
						format: "mediumThreeByTwo440",
						height: 293,
						width: 440,
					},
				],
			},
		],
		eta_id: 0,
	},
	{
		uri: "nyt://article/b7ada73c-d33d-59e7-9cd3-d152d0b1ef23",
		image: "",
		url: "https://www.nytimes.com/2024/02/17/business/economy/the-great-compression.html",
		id: 100000009307314,
		asset_id: 100000009307314,
		source: "New York Times",
		date: "2024-02-17",
		updated: "2024-02-18 13:53:09",
		section: "Business",
		subsection: "Economy",
		nytdsection: "business",
		adx_keywords:
			"Real Estate and Housing (Residential);Affordable Housing;Mortgages;Suburbs;Zoning;Sustainable Living;Building (Construction);Lennar Corporation;Bend (Ore);San Antonio (Tex);United States",
		column: null,
		author: "By Conor Dougherty",
		type: "Article",
		title: "The Great Compression",
		abstract: "Thanks to soaring housing prices, the era of the 400-square-foot subdivision house is upon us.",
		des_facet: [
			"Real Estate and Housing (Residential)",
			"Affordable Housing",
			"Mortgages",
			"Suburbs",
			"Zoning",
			"Sustainable Living",
			"Building (Construction)",
		],
		org_facet: ["Lennar Corporation"],
		per_facet: [],
		geo_facet: ["Bend (Ore)", "San Antonio (Tex)", "United States"],
		media: [
			{
				type: "image",
				subtype: "photo",
				caption: "Many small houses sit side by side in the Elm Trails subdivision from Lennar Homes in San Antonio.",
				copyright: "Josh Huskin for The New York Times",
				approved_for_syndication: 1,
				"media-metadata": [
					{
						url: "https://static01.nyt.com/images/2024/02/18/multimedia/18Smallhouses1-cover-qmfg/18Smallhouses1-cover-qmfg-thumbStandard-v2.jpg",
						format: "Standard Thumbnail",
						height: 75,
						width: 75,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/18/multimedia/18Smallhouses1-cover-qmfg/18Smallhouses1-cover-qmfg-mediumThreeByTwo210-v2.jpg",
						format: "mediumThreeByTwo210",
						height: 140,
						width: 210,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/18/multimedia/18Smallhouses1-cover-qmfg/18Smallhouses1-cover-qmfg-mediumThreeByTwo440-v2.jpg",
						format: "mediumThreeByTwo440",
						height: 293,
						width: 440,
					},
				],
			},
		],
		eta_id: 0,
	},
	{
		uri: "nyt://article/bd6dba04-f1b6-51f9-8992-f03845440811",
		image: "",
		url: "https://www.nytimes.com/2024/02/12/opinion/neuroscientist-on-biden-age-memory.html",
		id: 100000009308572,
		asset_id: 100000009308572,
		source: "New York Times",
		date: "2024-02-12",
		updated: "2024-02-14 12:50:43",
		section: "Opinion",
		subsection: "",
		nytdsection: "opinion",
		adx_keywords: "Memory;Presidential Election of 2024;Age, Chronological;Brain;Elderly;Biden, Joseph R Jr;Trump, Donald J",
		column: null,
		author: "By Charan Ranganath",
		type: "Article",
		title: "I’m a Neuroscientist. We’re Thinking About Biden’s Memory and Age in the Wrong Way.",
		abstract:
			"We are due for a national conversation, informed by science and not politics, about our expectations for our leaders’ cognitive and emotional health.",
		des_facet: ["Memory", "Presidential Election of 2024", "Age, Chronological", "Brain", "Elderly"],
		org_facet: [],
		per_facet: ["Biden, Joseph R Jr", "Trump, Donald J"],
		geo_facet: [],
		media: [
			{
				type: "image",
				subtype: "photo",
				caption: "",
				copyright: "Doug Mills/The New York Times",
				approved_for_syndication: 1,
				"media-metadata": [
					{
						url: "https://static01.nyt.com/images/2024/02/12/opinion/12ranganath/12ranganath-thumbStandard.jpg",
						format: "Standard Thumbnail",
						height: 75,
						width: 75,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/12/opinion/12ranganath/12ranganath-mediumThreeByTwo210.jpg",
						format: "mediumThreeByTwo210",
						height: 140,
						width: 210,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/12/opinion/12ranganath/12ranganath-mediumThreeByTwo440.jpg",
						format: "mediumThreeByTwo440",
						height: 293,
						width: 440,
					},
				],
			},
		],
		eta_id: 0,
	},
	{
		uri: "nyt://article/220550bb-d80e-5e8d-a0ab-dfac7da6fb28",
		image: "",
		url: "https://www.nytimes.com/2024/02/17/opinion/navalny-putin-trump.html",
		id: 100000009317044,
		asset_id: 100000009317044,
		source: "New York Times",
		date: "2024-02-17",
		updated: "2024-02-17 07:00:29",
		section: "Opinion",
		subsection: "",
		nytdsection: "opinion",
		adx_keywords: "Putin, Vladimir V;Navalny, Aleksei A;Trump, Donald J;Carlson, Tucker;Russia",
		column: null,
		author: "By Maureen Dowd",
		type: "Article",
		title: "The Florida Fraudster and the Russian ‘Killer’",
		abstract: "How do you like your pal, Putin, now, Trump?",
		des_facet: [],
		org_facet: [],
		per_facet: ["Putin, Vladimir V", "Navalny, Aleksei A", "Trump, Donald J", "Carlson, Tucker"],
		geo_facet: ["Russia"],
		media: [
			{
				type: "image",
				subtype: "photo",
				caption: "",
				copyright: "Doug Mills/The New York Times",
				approved_for_syndication: 1,
				"media-metadata": [
					{
						url: "https://static01.nyt.com/images/2024/02/18/multimedia/17dowd-klhw/17dowd-klhw-thumbStandard.jpg",
						format: "Standard Thumbnail",
						height: 75,
						width: 75,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/18/multimedia/17dowd-klhw/17dowd-klhw-mediumThreeByTwo210.jpg",
						format: "mediumThreeByTwo210",
						height: 140,
						width: 210,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/18/multimedia/17dowd-klhw/17dowd-klhw-mediumThreeByTwo440.jpg",
						format: "mediumThreeByTwo440",
						height: 293,
						width: 440,
					},
				],
			},
		],
		eta_id: 0,
	},
	{
		uri: "nyt://article/b4a00479-d6a2-5c36-b1a3-3f98af599b13",
		image: "",
		url: "https://www.nytimes.com/2024/02/12/us/politics/senate-ukraine-aid.html",
		id: 100000009309728,
		asset_id: 100000009309728,
		source: "New York Times",
		date: "2024-02-12",
		updated: "2024-02-13 11:32:42",
		section: "U.S.",
		subsection: "Politics",
		nytdsection: "u.s.",
		adx_keywords:
			"United States Politics and Government;Law and Legislation;Foreign Aid;Israel-Gaza War (2023- );Russian Invasion of Ukraine (2022);vis-video;McConnell, Mitch;Schumer, Charles E;Senate;House of Representatives;Republican Party;Democratic Party;Israel;Gaza Strip;Russia;Ukraine",
		column: null,
		author: "By Karoun Demirjian",
		type: "Article",
		title: "Senate Passes Aid to Ukraine, but Fate Is Uncertain in a Hostile House",
		abstract:
			"Democrats and a group of Republicans teamed up to approve the $95 billion bill, which also includes aid to Israel and civilians in conflict zones, but the House speaker threatened to ignore it.",
		des_facet: [
			"United States Politics and Government",
			"Law and Legislation",
			"Foreign Aid",
			"Israel-Gaza War (2023- )",
			"Russian Invasion of Ukraine (2022)",
			"vis-video",
		],
		org_facet: ["Senate", "House of Representatives", "Republican Party", "Democratic Party"],
		per_facet: ["McConnell, Mitch", "Schumer, Charles E"],
		geo_facet: ["Israel", "Gaza Strip", "Russia", "Ukraine"],
		media: [
			{
				type: "image",
				subtype: "photo",
				caption:
					"Senator Mitch McConnell, Republican of Kentucky and the minority leader, at the Capitol during the vote. He has vocally championed aiding Ukraine.",
				image: "",
				copyright: "Anna Rose Layden for The New York Times",
				approved_for_syndication: 1,
				"media-metadata": [
					{
						url: "https://static01.nyt.com/images/2024/03/12/multimedia/12dc-cong-01-ftmz/12dc-cong-01-ftmz-thumbStandard.jpg",
						format: "Standard Thumbnail",
						height: 75,
						width: 75,
					},
					{
						url: "https://static01.nyt.com/images/2024/03/12/multimedia/12dc-cong-01-ftmz/12dc-cong-01-ftmz-mediumThreeByTwo210.jpg",
						format: "mediumThreeByTwo210",
						height: 140,
						width: 210,
					},
					{
						url: "https://static01.nyt.com/images/2024/03/12/multimedia/12dc-cong-01-ftmz/12dc-cong-01-ftmz-mediumThreeByTwo440.jpg",
						format: "mediumThreeByTwo440",
						height: 293,
						width: 440,
					},
				],
			},
		],
		eta_id: 0,
	},
	{
		uri: "nyt://article/88d139e6-b416-5540-b1dc-75f2fa4602be",
		image: "",
		url: "https://www.nytimes.com/2024/02/16/nyregion/trump-civil-fraud-trial-ruling.html",
		id: 100000009306346,
		asset_id: 100000009306346,
		source: "New York Times",
		date: "2024-02-16",
		updated: "2024-02-17 12:40:42",
		section: "New York",
		subsection: "",
		nytdsection: "new york",
		adx_keywords:
			"New York State Civil Case Against Trump (452564/2022);Frauds and Swindling;Appraisals and Valuation (Property);Fines (Penalties);Decisions and Verdicts;Presidential Election of 2024;Courts and the Judiciary;Suits and Litigation (Civil);Compensation for Damages (Law);Trump, Donald J;Engoron, Arthur F;James, Letitia;Trump Organization;Manhattan (NYC)",
		column: null,
		author: "By Jonah E. Bromwich and Ben Protess",
		type: "Article",
		title: "Trump Fraud Trial Penalty Will Exceed $450 Million",
		abstract:
			"The ruling in Donald J. Trump’s civil fraud case could cost him all his available cash. The judge said that the former president’s “complete lack of contrition” bordered on pathological.",
		des_facet: [
			"New York State Civil Case Against Trump (452564/2022)",
			"Frauds and Swindling",
			"Appraisals and Valuation (Property)",
			"Fines (Penalties)",
			"Decisions and Verdicts",
			"Presidential Election of 2024",
			"Courts and the Judiciary",
			"Suits and Litigation (Civil)",
			"Compensation for Damages (Law)",
		],
		org_facet: ["Trump Organization"],
		per_facet: ["Trump, Donald J", "Engoron, Arthur F", "James, Letitia"],
		geo_facet: ["Manhattan (NYC)"],
		media: [
			{
				type: "image",
				subtype: "photo",
				caption:
					"The civil trial tested Donald J. Trump’s claims of wealth and a judge found them fraudulent. The former president is expected to appeal. ",
				copyright: "Maansi Srivastava/The New York Times",
				approved_for_syndication: 1,
				"media-metadata": [
					{
						url: "https://static01.nyt.com/images/2024/02/16/multimedia/16engoron-ledeall-01-qwtm/16engoron-ledeall-01-qwtm-thumbStandard.jpg",
						format: "Standard Thumbnail",
						height: 75,
						width: 75,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/16/multimedia/16engoron-ledeall-01-qwtm/16engoron-ledeall-01-qwtm-mediumThreeByTwo210.jpg",
						format: "mediumThreeByTwo210",
						height: 140,
						width: 210,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/16/multimedia/16engoron-ledeall-01-qwtm/16engoron-ledeall-01-qwtm-mediumThreeByTwo440.jpg",
						format: "mediumThreeByTwo440",
						height: 293,
						width: 440,
					},
				],
			},
		],
		eta_id: 0,
	},
	{
		uri: "nyt://article/d282450a-e8f5-523b-b335-ba2dffeb8636",
		image: "",
		url: "https://www.nytimes.com/2024/02/15/us/kansas-city-super-bowl-shooting.html",
		id: 100000009314685,
		asset_id: 100000009314685,
		source: "New York Times",
		date: "2024-02-15",
		updated: "2024-02-16 15:08:28",
		section: "U.S.",
		subsection: "",
		nytdsection: "u.s.",
		adx_keywords: "Super Bowl;Football;Parades;Kansas City, Mo, Shooting (Feb 14, 2024);Kansas City Chiefs;Kansas City (Mo)",
		column: null,
		author: "By Nicholas Bogel-Burroughs, Jacey Fortin, Kevin Draper and Colbi Edmonds",
		type: "Article",
		title: "2 Teens in Custody in Kansas City, Where Police Say Dispute Led to Shooting",
		abstract:
			"The authorities said they were working to determine “applicable charges” in the shooting that followed a Super Bowl victory parade. The host of a local radio show was killed, and 22 more were injured.",
		des_facet: ["Super Bowl", "Football", "Parades", "Kansas City, Mo, Shooting (Feb 14, 2024)"],
		org_facet: ["Kansas City Chiefs"],
		per_facet: [],
		geo_facet: ["Kansas City (Mo)"],
		media: [],
		eta_id: 0,
	},
	{
		uri: "nyt://article/d1aacd26-72ed-50b9-afd1-3496489c42ef",
		image: "",
		url: "https://www.nytimes.com/2024/02/13/well/advil-ibuprofen-health-risks.html",
		id: 100000009276043,
		asset_id: 100000009276043,
		source: "New York Times",
		date: "2024-02-13",
		updated: "2024-02-13 05:00:28",
		section: "Well",
		subsection: "",
		nytdsection: "well",
		adx_keywords: "Ibuprofen (Drug);Nonsteroidal Anti-inflammatory Drugs (NSAIDs);Kidneys;Heart;Stomach;Ulcers;Content Type: Service;Accidents and Safety",
		column: null,
		author: "By Melinda Wenner Moyer",
		type: "Article",
		title: "How Much Advil Is Too Much?",
		abstract: "Ibuprofen can be a blessing for those with aches and pains, but overdoing it poses serious risks.",
		des_facet: [
			"Ibuprofen (Drug)",
			"Nonsteroidal Anti-inflammatory Drugs (NSAIDs)",
			"Kidneys",
			"Heart",
			"Stomach",
			"Ulcers",
			"Content Type: Service",
			"Accidents and Safety",
		],
		org_facet: [],
		per_facet: [],
		geo_facet: [],
		media: [
			{
				type: "image",
				subtype: "photo",
				caption: "",
				copyright: "Eric Helgas for The New York Times",
				approved_for_syndication: 1,
				"media-metadata": [
					{
						url: "https://static01.nyt.com/images/2024/02/01/multimedia/ASKWELL-ADVIL-2-hwft/ASKWELL-ADVIL-2-hwft-thumbStandard.jpg",
						format: "Standard Thumbnail",
						height: 75,
						width: 75,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/01/multimedia/ASKWELL-ADVIL-2-hwft/ASKWELL-ADVIL-2-hwft-mediumThreeByTwo210.jpg",
						format: "mediumThreeByTwo210",
						height: 140,
						width: 210,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/01/multimedia/ASKWELL-ADVIL-2-hwft/ASKWELL-ADVIL-2-hwft-mediumThreeByTwo440.jpg",
						format: "mediumThreeByTwo440",
						height: 293,
						width: 440,
					},
				],
			},
		],
		eta_id: 0,
	},
	{
		uri: "nyt://article/8966882e-e466-5dfc-ae71-e18814098479",
		image: "",
		url: "https://www.nytimes.com/2024/02/12/style/millennial-gen-z-style.html",
		id: 100000009306612,
		asset_id: 100000009306612,
		source: "New York Times",
		date: "2024-02-12",
		updated: "2024-02-14 15:50:12",
		section: "Style",
		subsection: "",
		nytdsection: "style",
		adx_keywords: "Fashion and Apparel;Millennial Generation;Generation Z;Content Type: Service",
		column: null,
		author: "By Vanessa Friedman",
		type: "Article",
		title: "How Can I Update My Millennial Style?",
		abstract: "Our fashion critic encourages a reader to invest in timeless pieces instead of getting caught up in generational stereotypes.",
		des_facet: ["Fashion and Apparel", "Millennial Generation", "Generation Z", "Content Type: Service"],
		org_facet: [],
		per_facet: [],
		geo_facet: [],
		media: [
			{
				type: "image",
				subtype: "photo",
				caption: "Catherine, Princess of Wales, in a grown-up suit last fall.",
				copyright: "Chris Jackson/Chris Jackson Collection, via Getty Images",
				approved_for_syndication: 1,
				"media-metadata": [
					{
						url: "https://static01.nyt.com/images/2024/02/09/multimedia/09Openthread-gfcz/09Openthread-gfcz-thumbStandard.jpg",
						format: "Standard Thumbnail",
						height: 75,
						width: 75,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/09/multimedia/09Openthread-gfcz/09Openthread-gfcz-mediumThreeByTwo210.jpg",
						format: "mediumThreeByTwo210",
						height: 140,
						width: 210,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/09/multimedia/09Openthread-gfcz/09Openthread-gfcz-mediumThreeByTwo440.jpg",
						format: "mediumThreeByTwo440",
						height: 293,
						width: 440,
					},
				],
			},
		],
		eta_id: 0,
	},
	{
		uri: "nyt://interactive/34636850-3a4d-5dcc-9997-235047f07e58",
		image: "",
		url: "https://www.nytimes.com/interactive/2024/02/16/briefing/news-quiz-congress-israel.html",
		id: 100000009316402,
		asset_id: 100000009316402,
		source: "New York Times",
		date: "2024-02-16",
		updated: "2024-02-16 10:13:13",
		section: "Briefing",
		subsection: "",
		nytdsection: "briefing",
		adx_keywords: "Content Type: Quiz",
		column: null,
		author: "",
		type: "Interactive",
		title: "The New York Times News Quiz, Feb. 16, 2024",
		abstract: "Did you follow the news this week? Take our quiz to see how well you stack up with other Times readers.",
		des_facet: ["Content Type: Quiz"],
		org_facet: [],
		per_facet: [],
		geo_facet: [],
		media: [
			{
				type: "image",
				subtype: "",
				caption: "",
				copyright: "Anna Watts for The New York Times",
				approved_for_syndication: 1,
				"media-metadata": [
					{
						url: "https://static01.nyt.com/images/2024/02/15/multimedia/15newsquiz-Suozzi-wzhp/15newsquiz-Suozzi-wzhp-thumbStandard.jpg",
						format: "Standard Thumbnail",
						height: 75,
						width: 75,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/15/multimedia/15newsquiz-Suozzi-wzhp/15newsquiz-Suozzi-wzhp-mediumThreeByTwo210.jpg",
						format: "mediumThreeByTwo210",
						height: 140,
						width: 210,
					},
					{
						url: "https://static01.nyt.com/images/2024/02/15/multimedia/15newsquiz-Suozzi-wzhp/15newsquiz-Suozzi-wzhp-mediumThreeByTwo440.jpg",
						format: "mediumThreeByTwo440",
						height: 293,
						width: 440,
					},
				],
			},
		],
		eta_id: 0,
	},
];

export default function Home() {
	return (
		<section className="container my-10">
			<h1>Welcome to news app</h1>
			<ArticlesList articles={articles} small={false} />
		</section>
	);
}
